name = "Weapons-Balance-IFA-RP"
prefix = "wb_ifa_rp"
author = "johnb43"
template = "cba"
mainprefix = "z"
files = [
    "CHANGELOG.md",
    "mod.cpp",
    "LICENSE",
    "README.md"
]
folder_optionals = false
sig_version = 3
